Update 653

diff --git a/.github/workflows/sonar-gate.yml b/.github/workflows/sonar-gate.yml
--- a/.github/workflows/sonar-gate.yml
+++ b/.github/workflows/sonar-gate.yml
@@ -3,7 +3,7 @@ name: CI Pipeline
 on: [push, pull_request]
 
 jobs:
-  sonar:
+  sonarQubeAnalysis:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout code
@@ -25,21 +25,54 @@ jobs:
           -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
 
-    - name: SonarQube Quality Gate check
-      id: sonarqube-quality-gate-check
-      uses: sonarsource/sonarqube-quality-gate-action@master
-      env:
-       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #OPTIONAL
-       SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
+    - name: Check Quality Gate
+      id: quality_gate
+      run: |
+        curl -u ${{ secrets.SONAR_TOKEN }}: \
+          "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=my-Java-web-app" \
+          -o sonar.json
+        echo "SonarQube API Response:"
+        cat sonar.json # Print the content of the JSON file for debugging
+        qualityGateStatus=$(jq -r '.projectStatus.status' sonar.json || echo 'error')
+        if [ "$qualityGateStatus" = "error" ]; then
+          echo "Failed to parse JSON. Exiting."
+          exit 1
+        fi
+        echo "Quality Gate Status: $qualityGateStatus"
+        if [ "$qualityGateStatus" != "OK" ]; then
+          echo "Quality Gate failed"
+          exit 1
+        fi
+
+  notify:
+    runs-on: ubuntu-latest
+    needs: sonarQubeAnalysis
+    if: failure()
+    steps:
+    - name: Send Notification Email
+      uses: dawidd6/action-send-mail@v3
+      with:
+        server_address: smtp.gmail.com
+        server_port: 587
+        username: ${{ secrets.SMTP_LOGIN }}
+        password: ${{ secrets.SMTP_PASSWORD }}
+        subject: Quality Gate Failure
+        body: Quality Gate failed for project my-project
+        to: venkateshg9430@gmail.com
+        from: venkateshg9430@gmail.com
 
   build:
     runs-on: ubuntu-latest
-    needs: sonar
-    if: ${{ needs.sonar.outputs.quality_gate == 'OK' }}
+    needs: sonarQubeAnalysis
+    if: success()
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
+
+    - name: Set up JDK 11
+      uses: actions/setup-java@v2
+      with:
+        java-version: '11'
 
     - name: Set up Node.js
       uses: actions/setup-node@v2
@@ -51,13 +84,3 @@ jobs:
 
     - name: Build
       run: npm run build
-
-  notify:
-    runs-on: ubuntu-latest
-    needs: sonar
-    if: ${{ needs.sonar.outputs.quality_gate != 'OK' }}
-    steps:
-    - name: Notify developers
-      run: |
-        echo "SonarQube quality gate failed. Please check the logs."
-        curl -X POST -H 'Content-type: application/json' --data '{"text":"SonarQube quality gate failed. Please check the logs."}'
