Update 458

diff --git a/.github/workflows/sonar-gate.yml b/.github/workflows/sonar-gate.yml
--- a/.github/workflows/sonar-gate.yml
+++ b/.github/workflows/sonar-gate.yml
@@ -34,13 +34,13 @@ jobs:
       run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
     
     - name: Check SonarQube Quality Gate status
-      run: 
-       STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status')
-       if [ "$STATUS" != "OK" ]; then
-         echo "Quality Gate failed"
-         exit 1
-       fi
-jobs:
+      run:
+        sudo apt-get install -y jq
+        STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}:"${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status'
+        if [ "$STATUS" != "OK" ]; then
+          echo "Quality Gate failed"
+          exit 1
+        fi
   build:
     runs-on: ubuntu-latest
     steps:
